# Generated by Django 5.0.6 on 2024-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_remove_aluno_dia_remove_aluno_horario_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='horarios', to='alunos.aluno'),
        ),
    ]
