# Generated by Django 5.0.6 on 2024-05-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_horario_alunos'),
        ('alunos', '0005_populate_db'),
    ]

    operations = [
    ]
