# Generated by Django 5.0.6 on 2024-05-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_merge_0004_horario_alunos_0005_populate_db'),
        ('alunos', '0007_excluir_nomes'),
    ]

    operations = [
    ]
