# Generated by Django 5.0.6 on 2024-05-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_merge_20240529_1902'),
        ('alunos', '0009_remove_table'),
    ]

    operations = [
    ]
