"""Add attendance_status to Student

Revision ID: 62c27c9f3cf1
Revises: 833ad375d292
Create Date: 2024-11-05 23:08:39.757920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c27c9f3cf1'
down_revision = '833ad375d292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('class_shift',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_index('ix_student_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('ix_student_name', ['name'], unique=False)
        batch_op.alter_column('class_shift',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
