"""Add attendance_status to Student model

Revision ID: 833ad375d292
Revises: 95d4179498e6
Create Date: 2024-11-05 20:51:34.762656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833ad375d292'
down_revision = '95d4179498e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('attendance_status')

    # ### end Alembic commands ###
